In [1]:
import numpy

## [argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

numpy.argsort(array_like,axis=01,kind=None,order=None)

Parameters :
- axis
    - -1 : last axis, default
    - 0 : row
    - 1 : column
- kind:optional
    - quicksort : default
    - mergesort
    - heapsort
    - stable : ?
- order:optional
    - str or list of str 

Returns: `index_array`



In [3]:
x = numpy.array([[0,3],[2,2]])
x

array([[0, 3],
       [2, 2]])

In [4]:
ind = numpy.argsort(x,axis=0) # 열기반 높으면 1, 같으면 선행되는게 큰걸로 치나??
ind


array([[0, 1],
       [1, 0]])

In [5]:
numpy.take_along_axis(x,ind,axis=0) # x의 0,2,3 value가 ind에서의 자리대로 들어간다.

array([[0, 2],
       [2, 3]])

In [7]:
ind = numpy.argsort(x,axis=1)
ind

array([[0, 1],
       [0, 1]])

In [8]:
numpy.take_along_axis(x,ind,axis=1)

array([[0, 3],
       [2, 2]])