# Numpy

```{figure} https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F3%2F31%2FNumPy_logo_2020.svg%2F1200px-NumPy_logo_2020.svg.png&tbnid=ZT36fhhFxV1DWM&vet=12ahUKEwi68dOK1_yBAxU0XvUHHSZHC8kQMygAegQIARBN..i&imgrefurl=https%3A%2F%2Fko.wikipedia.org%2Fwiki%2FNumPy&docid=7dPAX9mpNAHBJM&w=1200&h=540&q=numpy&ved=2ahUKEwi68dOK1_yBAxU0XvUHHSZHC8kQMygAegQIARBN
```

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
print(x, type(x))

y = np.array([2, 4, 

SyntaxError: incomplete input (1786702645.py, line 4)

## [argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

numpy.argsort(array_like,axis=01,kind=None,order=None)

Parameters :
- axis
    - -1 : last axis, default
    - 0 : row
    - 1 : column
- kind:optional
    - quicksort : default
    - mergesort
    - heapsort
    - stable : ?
- order:optional
    - str or list of str 

Returns: `index_array`



In [3]:
x = numpy.array([[0,3],[2,2]])
x

array([[0, 3],
       [2, 2]])

In [4]:
ind = numpy.argsort(x,axis=0) # 열기반 높으면 1, 같으면 선행되는게 큰걸로 치나??
ind


array([[0, 1],
       [1, 0]])

In [5]:
numpy.take_along_axis(x,ind,axis=0) # x의 0,2,3 value가 ind에서의 자리대로 들어간다.

array([[0, 2],
       [2, 3]])

In [7]:
ind = numpy.argsort(x,axis=1)
ind

array([[0, 1],
       [0, 1]])

In [8]:
numpy.take_along_axis(x,ind,axis=1)

array([[0, 3],
       [2, 2]])